name : "Terraform CD"

on:
  push:
    branches: -main
  workflow_dispatch: "Run Workflow"

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3

  - name: Terraform Init
    run: terraform init

  - name: Terraform Validate
    run: terraform validate

  - name: Terraform Plan
    run: terraform plan -out=tfplan

  - name: Terraform Apply
    # This step only executes if the previous steps passed
    run: terraform apply -auto-approve tfplan